In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy

In [4]:
array1 = numpy.array([2, 3, 2, 2,])

array1
type(array1)
array1.shape
array1.size
array1.ndim

array([2, 3, 2, 2])

numpy.ndarray

(4,)

4

1

In [10]:
array2 = numpy.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

array2
type(array2)
array2.shape
array2.size # total

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

numpy.ndarray

(3, 4)

12

In [11]:
array3 = numpy.full(6, 7)

array3
type(array3)
array3.shape
array3.size

array([7, 7, 7, 7, 7, 7])

numpy.ndarray

(6,)

6

In [12]:
array4 = numpy.full(6, 0)
array5 = numpy.zeros(6, dtype=int)

array4
array5

array([0, 0, 0, 0, 0, 0])

array([0, 0, 0, 0, 0, 0])

In [13]:
array6 = numpy.full(6, 1)
array7 = numpy.ones(6, dtype=int)

array6
array7

array([1, 1, 1, 1, 1, 1])

array([1, 1, 1, 1, 1, 1])

In [14]:
array8 = numpy.random.random(6)
array8

array([0.15216539, 0.76550961, 0.11444186, 0.95435584, 0.35247751,
       0.72600785])

In [17]:
array9 = numpy.arange(6) # arange(n) : 1 ~ n-1
array10 = numpy.arange(2, 7) #arange(n, m) : n ~ m-1
array11 = numpy.arange(3, 17, 3) # arange(n, m, l) : n ~ m-1, stride l

array9
array10
array11

array([0, 1, 2, 3, 4, 5])

array([2, 3, 4, 5, 6])

array([ 3,  6,  9, 12, 15])

In [18]:
# 09. Indexing
array1

array([2, 3, 2, 2])

In [19]:
array1[[0, 1, 2]]

array([2, 3, 2])

In [31]:
import numpy as np
# 15. Boolean Operation
array1 = np.array([2, 3, 4, 5, 6, 8, 9, 10])
array1 > 6

array([False, False, False, False, False,  True,  True,  True])

In [32]:
np.where(array1 > 6) # works as a filter
type(np.where(array1 > 6))
filter_ = np.where(array1 > 6)
type(filter_)
array1[filter_]

(array([5, 6, 7], dtype=int64),)

tuple

tuple

array([ 8,  9, 10])

In [34]:
revenue_in_yen = [
    300000, 340000, 320000, 360000, 
    440000, 140000, 180000, 340000, 
    330000, 290000, 280000, 380000, 
    170000, 140000, 230000, 390000, 
    400000, 350000, 380000, 150000, 
    110000, 240000, 380000, 380000, 
    340000, 420000, 150000, 130000, 
    360000, 320000, 250000
]

# 코드를 작성하세요.
bad_days_revenue = np.array(revenue_in_yen)[np.where(np.array(revenue_in_yen) < 200000)]
# or
bad_days_revenue = np.array(revenue_in_yen)[np.array(revenue_in_yen) < 200000]
bad_days_revenue # 정답 출력

# np.where(condition) : tuple
# condition : numpy array

array([140000, 180000, 170000, 140000, 150000, 110000, 150000, 130000])

In [35]:
array1.max()
array1.min()

10

2

In [40]:
array1.mean()
np.median(array1)
# mean vs. median
# mean : built in for each variable
# median : only in the module

5.875

5.5